CREATE TABLE Categories (
	[UuId] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	[ParentUuId] INT NULL,
	[Name] NVARCHAR (MAX) NOT NULL,
	[Description] NVARCHAR (MAX) NULL,
	[KeyWords] NVARCHAR (MAX) NULL,
	[IsDeleted] Bit NOT NULL DEFAULT 0)