use StoreDB
CREATE TABLE Products (
	[UuId] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	[Name] NVARCHAR (MAX) NOT NULL,
	[Article] NVARCHAR (MAX) NULL,
	[BrandUuId] UNIQUEIDENTIFIER NULL,
	[CategoryUuId] UNIQUEIDENTIFIER NULL,
	[Description] NVARCHAR (MAX) NULL,
	[Price] DECIMAL NULL,
	FOREIGN KEY (BrandUuId) REFERENCES Brands (UuId),
	FOREIGN KEY (CategoryUuId) REFERENCES Categories (UuId))